// tests/capture-quality.test.js — UNI-225.
//
// 7 of 29 sampled institutions returned CloudFront/Cloudflare "403 Request blocked" on EVERY page.
// A blocked page carries no technology markers, so without this classification the tiered runner
// would exhaust all five pages and then report "no CMS" for an institution it never actually saw.
const { test } = require('node:test');
const assert = require('node:assert');
const path = require('path');
const { classifyCapture } = require(path.resolve(__dirname, '../src/capture-quality.js'));

// The real 923-byte capture archived for institution 1091, trimmed to its identifying parts.
const CLOUDFRONT_BLOCK = `<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head><title>ERROR: The request could not be satisfied</title></head><body>
<h1>403 ERROR</h1><h2>The request could not be satisfied.</h2>
Request blocked.
<pre>Generated by cloudfront (CloudFront)</pre></body></html>`;

const CLOUDFLARE_INTERSTITIAL =
  `<html><head><title>Just a moment...</title></head><body>${'x'.repeat(20000)}</body></html>`;

const REAL_PAGE =
  `<html><head><title>Riverside State University</title></head><body>${'x'.repeat(30000)}</body></html>`;

test('a CloudFront block capture is not scannable', () => {
  const { scannable, reason } = classifyCapture(CLOUDFRONT_BLOCK);
  assert.strictEqual(scannable, false);
  assert.ok(reason, 'a rejection must carry a reason');
});

test('a large Cloudflare interstitial is not scannable despite passing the size floor', () => {
  // Size alone cannot catch this one: it is 20 KB. The title signature is what catches it.
  const { scannable, reason } = classifyCapture(CLOUDFLARE_INTERSTITIAL);
  assert.strictEqual(scannable, false);
  assert.strictEqual(reason, 'blocked');
});

test('a real page is scannable', () => {
  assert.deepStrictEqual(classifyCapture(REAL_PAGE), { scannable: true, reason: null });
});

test('an empty capture is not scannable', () => {
  assert.strictEqual(classifyCapture('').scannable, false);
  assert.strictEqual(classifyCapture(null).scannable, false);
});

test('block wording in a real page body does not condemn the page', () => {
  // A .edu IT-support page may legitimately quote "403 ERROR" and "Request blocked" in its help
  // content. Signatures are matched against the <title> ONLY, so body text cannot false-block.
  // (Known, accepted trade-off: a page whose TITLE quotes that wording is still rejected.)
  const helpDesk = `<html><head><title>Riverside IT Help Desk</title></head>` +
    `<body>If you see "403 ERROR" or "Request blocked", contact the help desk.${'x'.repeat(30000)}</body></html>`;
  assert.strictEqual(classifyCapture(helpDesk).scannable, true, 'body wording must not block a real page');
});
